### ISSUE TITLE
Sanitize body

### ISSUE THREAD

**Issue by janvernieuwe** [allejo/php-vcr-sanitizer#1]
Hi!
Thanks for providing this much needed lib!

Are you planning on adding a body scrubber too (Or accept a PR for it? If i have the time), perhaps push the body trough a callable so users can filter out any sensitive data they might have there themselves?

**Comment by allejo** [comment]
Can't say I ever had plans of adding a way to scrub the body of the request but that's only because I've never had the need to. I'm open to adding support for this, sounds like a great addition. I'd gladly accept a PR for this. If not, I could take a look at adding this some time this week. 👍

What did you have in mind for usage? Something like this?

```php
VCRCleaner::enable(array(
    'ignoreUrlParameters' => array(
        'apiKey',
    ),
    'bodyScrubber' => function (&$body) {
        // ...modify $body
    },
));
```

**Comment by janvernieuwe** [comment]
Yes, something along those lines.
I'll try and create a PR today, thanks for the consideration!

**Comment by janvernieuwe** [comment]
Done, another possible nice addition would be to be able to sanitize the post fields, but I personally don't need that.
The body scrubbing is going to be very handy for sanitizing SOAP bodies :)

**Comment by allejo** [comment]
> another possible nice addition would be to be able to sanitize the post fields, but I personally don't need that.

I just checked and php-vcr stores POST fields inside of `body` as form encoded parameters, so `bodyScrubbers` should be able to handle that too.
