### ISSUE TITLE
Symfony 5

### ISSUE THREAD

**Issue by janvernieuwe** [allejo/php-vcr-sanitizer#12]
I'm trying to get everything to SF5, the event dispatcher has been changed.
So we either need a new major version for SF support, or a shim for the events.

I know that php-vcr is not ready yet for SF5 as we speak, but I hope I or someone else can make it work soon.

**Comment by allejo** [comment]
Since we support so many different versions of EventDispatcher. We'll continue to support whichever are still covered by Symfony LTS (3.4 and 4.4 currently) and add a shim to handle SF5.

https://github.com/allejo/php-vcr-sanitizer/blob/b8f88990c74af40191bc432fabc5b1c266830471/composer.json#L7

---

Looks like changes may need to happen at the php-vcr level on how events dispatched? I need to research this a bit more.

See: https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

**Comment by pauladams8** [comment]
I submitted a PR to VCR a few days ago to support Symfony 5 (see https://github.com/php-vcr/php-vcr/pull/311) and don't think it'll affect this package. I'm currently using my own fork of this package which is on Symfony 5 and it all works fine so if my PR is merged it should be safe to update.

**Comment by allejo** [comment]
> don't think it'll affect this package

~~I don't think this is true. From the little I've seen, the namespace and signature of EventDispatcher has changed in 5.x, which I think will break in this package's event subscriber.~~

Ah my apologies, spoke too soon. The interfaces for event subscribers have remained unchanged. So this package should support Symfony 5.x no problem once php-vcr supports it 🎉

**Comment by pauladams8** [comment]
The only breaking changes in Symfony 5 as far as I could see are the signature of the `Event` class and the `dispatch()` method of the event dispatcher, neither of which this package uses.

**Comment by allejo** [comment]
Since it appears this package doesn't need make any changes to support SF5, I'll close this issue.
